package com.musicdrop.tv.data.youtube.potoken

import android.content.Context

/**
 * Allows generating poTokens with a previously-obtained `integrityToken` and
 * `webPoSignalOutput`. Ported from NewPipe's util/potoken/PoTokenGenerator.kt, adapted
 * from RxJava Singles to Kotlin coroutines.
 */
interface PoTokenGenerator : AutoCloseable {
    /**
     * Generates a poToken for the provided identifier. Can be called multiple times
     * (also concurrently) as long as the generator is not expired or closed.
     */
    suspend fun generatePoToken(identifier: String): String

    /**
     * @return whether the `integrityToken` is expired, in which case all tokens generated by
     * [generatePoToken] will be invalid and a new generator must be created.
     */
    fun isExpired(): Boolean

    override fun close()

    companion object {
        /**
         * Initializes a [PoTokenGenerator] by loading the BotGuard VM into an offscreen WebView,
         * running it, and obtaining an `integrityToken`. Must not be called from the main thread.
         */
        suspend fun newPoTokenGenerator(context: Context): PoTokenGenerator =
            PoTokenWebView.newPoTokenGenerator(context)
    }
}
